baseURL: https://eshaan7.github.io/blog/
languageCode: en-us
title: Eshaan Bansal
theme: vanilla-bootstrap-hugo-theme
publishDir: docs
# googleAnalytics: UA-123456789-1

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

# See https://feathericons.com/
# The value of pre is the icon name
menu:
  nav:
  # - name: Home
  #   pre: home
  #   url: /
  #   weight: 1
  - name: Posts
    pre: edit
    url: /post/
    weight: 1
  - name: Tags
    pre: tag
    url: /tags/
    weight: 2
  - name: About
    pre: smile
    url: https://eshaan7.github.io/
    weight: 3

params:
  includeBootstrapJs: false
  enableParticlesJs: true
  showActiveNav: true
  containerMaxWidth: 700px
  dateFormat: Jan 2, 2006
  homeText: Hi, I'm Eshaan! I write, sometimes.
  footerText: Eshaan Bansal - eshaan7bansal@gmail.com - https://eshaan7.github.io/
  #footerText: Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)
  hideFooter: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
